#!/usr/bin/env python3
"""Generate the checked Python and TypeScript Pisec operation projections."""

from __future__ import annotations

import argparse
import hashlib
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "pisec" / "operation-catalogue.json"
PYTHON_OUTPUT = ROOT / "scripts" / "pisec" / "operation_catalogue_generated.py"
TYPESCRIPT_OUTPUT = ROOT / "omp" / "extensions" / "pisec-operation-catalogue.generated.ts"


def _load() -> tuple[list[dict[str, object]], str]:
    raw = SOURCE.read_bytes()
    value = json.loads(raw)
    entries = value.get("entries") if isinstance(value, dict) else None
    if not isinstance(entries, list) or not entries:
        raise SystemExit("operation catalogue must contain a non-empty entries list")
    required = {"socket", "operation", "tool", "role", "purpose"}
    seen: set[tuple[str, str]] = set()
    normalized: list[dict[str, object]] = []
    for entry in entries:
        if not isinstance(entry, dict) or set(entry) != required:
            raise SystemExit("operation catalogue entry fields are invalid")
        key = (str(entry["socket"]), str(entry["operation"]))
        if key in seen:
            raise SystemExit(f"duplicate operation catalogue entry: {key}")
        seen.add(key)
        normalized.append({key: entry[key] for key in sorted(entry)})
    normalized.sort(key=lambda item: (str(item["socket"]), str(item["operation"])))
    canonical = json.dumps({"entries": normalized}, sort_keys=True, separators=(",", ":"))
    return normalized, hashlib.sha256(canonical.encode()).hexdigest()


def _python(entries: list[dict[str, object]], digest: str) -> str:
    sockets: dict[str, list[str]] = {}
    for entry in entries:
        sockets.setdefault(str(entry["socket"]), []).append(str(entry["operation"]))
    return "# Generated by scripts/generate-pisec-operation-catalogue.py; do not edit.\n" + f"CATALOGUE_SHA256 = {digest!r}\n" + f"ENTRIES = {tuple(entries)!r}\n" + f"SOCKET_OPERATIONS = {{\n" + "".join(f"    {socket!r}: frozenset({tuple(values)!r}),\n" for socket, values in sorted(sockets.items())) + "}\n"


def _typescript(entries: list[dict[str, object]], digest: str) -> str:
    body = json.dumps(entries, ensure_ascii=False, sort_keys=True, indent=2)
    return "// Generated by scripts/generate-pisec-operation-catalogue.py; do not edit.\n" + f"export const PISEC_OPERATION_CATALOGUE_SHA256 = {digest!r};\n" + f"export const PISEC_OPERATION_CATALOGUE = {body} as const;\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    entries, digest = _load()
    expected = {PYTHON_OUTPUT: _python(entries, digest), TYPESCRIPT_OUTPUT: _typescript(entries, digest)}
    mismatches = [str(path) for path, content in expected.items() if not path.is_file() or path.read_text(encoding="utf-8") != content]
    if args.check:
        if mismatches:
            print("operation catalogue generated outputs are stale: " + ", ".join(mismatches), file=sys.stderr)
            return 1
        return 0
    for path, content in expected.items():
        path.write_text(content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
